# journal_backend Dockerfile
FROM python:3.13

WORKDIR /app

COPY journal_backend/ /app/

RUN pip install -r requirements.txt

RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "journal_backend.wsgi:application", "--bind", "0.0.0.0:8000"]