services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - static_volume:/app/static
    env_file:
      - ./journal_backend/.env
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  static_volume:
