# Generated by Django 5.2 on 2025-05-11 21:40

import django.db.models.deletion
import journals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('number', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('ssn', models.CharField(blank=True, default='2249-104X', max_length=20, null=True)),
                ('pdf_file', models.FileField(upload_to='journals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=2025, help_text='Enter the publication year (e.g., 2023)', validators=[journals.models.validate_year])),
                ('period', models.CharField(choices=[('jan-jun', 'January - June'), ('jul-dec', 'July - December')], default='jan-jun', max_length=7)),
            ],
            options={
                'unique_together': {('volume', 'number', 'year', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='temp_pdfs/')),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journals.journal')),
                ('tags', models.ManyToManyField(blank=True, to='journals.tag')),
            ],
            options={
                'ordering': ['article_number'],
            },
        ),
    ]
