# Generated by Django 5.2 on 2025-04-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('number', models.IntegerField()),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='temp_pdfs/')),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journals.journal')),
                ('tags', models.ManyToManyField(blank=True, to='journals.tag')),
            ],
            options={
                'ordering': ['article_number'],
            },
        ),
    ]
