# Generated by Django 5.2 on 2025-05-03 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='pdf_file',
            field=models.FileField(default='', upload_to='journals/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
