# Generated by Django 5.2 on 2025-05-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_journal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='year',
            field=models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')]),
        ),
    ]
