# Generated by Django 5.2 on 2025-05-11 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_journal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='year',
            field=models.IntegerField(default=2025, help_text='Enter the publication year (e.g., 2023)', validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
